image: golang:latest

variables:
  BINARY: freya-rest-api
  REPO_NAME: github.com/dafian47/go-freya-rest-api

before_script:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - dep ensure

stages:
  - test
  - build

test_project:
  stage: test
  script:
    - make test

build_project:
  stage: build
  script:
    - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/$BINARY
  only:
      - tags
  artifacts:
    expire_in: 1 week
    paths:
      - $BINARY
