image: golang:latest

variables:
  BINARY: freya-rest-api
  REPO_NAME: github.com/dafian47/go-freya-rest-api

before_script:
  - go get -u github.com/kardianos/govendor
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - govendor sync

stages:
  - test
  - build

test_project:
  stage: test
  script:
    #- go fmt $(go list ./... | grep -v /vendor/)
    #- go vet $(go list ./... | grep -v /vendor/)
    #- go test -race $(go list ./... | grep -v /vendor/)
    - make test

build_project:
  stage: build
  script:
    - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/$BINARY
  only:
      - tags
  artifacts:
    expire_in: 1 week
    paths:
      - $BINARY
